import { useEffect, useState } from 'react';
import { Check, ClipboardCheck, X } from 'lucide-react';
import Sidebar from '../components/Sidebar.jsx';
import TopBar from '../components/TopBar.jsx';
import { listAttendanceCorrections, reviewAttendanceCorrection } from '../services/api.js';

export default function CorrectionRequestsPage() {
  const [requests, setRequests] = useState([]); const [message, setMessage] = useState('');
  const load = () => listAttendanceCorrections().then(setRequests).catch((e) => setMessage(e.message));
  useEffect(() => { load(); }, []);
  async function review(item, status) { const reviewNote = window.prompt(`${status === 'APPROVED' ? 'Approve' : 'Reject'} request: add a note`); if (!reviewNote) return; try { await reviewAttendanceCorrection(item.id, { status, reviewNote }); setMessage(`Request ${status.toLowerCase()}.`); await load(); } catch (e) { setMessage(e.message || 'Could not review request'); } }
  return <div className="flex min-h-screen bg-ink-950"><Sidebar/><main className="min-w-0 flex-1 pb-10"><TopBar connected/><div className="mx-auto mt-6 max-w-6xl px-8"><div className="mb-6"><h1 className="flex items-center gap-2 text-xl font-bold text-white"><ClipboardCheck className="text-signal-blue"/>Attendance Correction Inbox</h1><p className="mt-1 text-sm text-slate-400">Review missed-attendance reports for sessions assigned to you.</p></div>{message && <p className="mb-4 rounded-xl border border-signal-blue/20 bg-signal-blue/10 p-3 text-sm text-slate-200">{message}</p>}<div className="overflow-x-auto rounded-2xl border border-ink-border bg-ink-850/60"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="text-slate-400">{['Student','Session','Reason','Submitted','Status','Review'].map((x) => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{requests.map((item) => <tr key={item.id} className="border-t border-ink-border"><td className="px-4 py-3 text-white">{item.student.name}<br/><span className="text-xs text-slate-500">{item.student.rollNo}</span></td><td className="px-4 py-3 text-slate-300">{item.session.subject.code}<br/><span className="text-xs text-slate-500">{new Date(item.session.startedAt).toLocaleString('en-IN')}</span></td><td className="max-w-xs px-4 py-3 text-slate-300">{item.reason}</td><td className="px-4 py-3 text-slate-500">{new Date(item.createdAt).toLocaleDateString('en-IN')}</td><td className="px-4 py-3 font-bold text-signal-blue">{item.status}</td><td className="px-4 py-3">{item.status === 'PENDING' ? <div className="flex gap-2"><button onClick={() => review(item, 'APPROVED')} title="Approve" className="text-signal-green"><Check/></button><button onClick={() => review(item, 'REJECTED')} title="Reject" className="text-signal-red"><X/></button></div> : <span className="text-xs text-slate-500">{item.reviewNote || '—'}</span>}</td></tr>)}</tbody></table>{!requests.length && <p className="p-8 text-center text-slate-500">No attendance corrections pending.</p>}</div></div></main></div>;
}
