import { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { getMyAttendance } from '../services/api.js';

export default function StudentAttendancePage() {
  const navigate = useNavigate(); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getMyAttendance().then(setData).catch((err) => setError(err.message)); }, []);
  return <div className="min-h-screen bg-ink-950 px-5 py-8 text-slate-200"><main className="mx-auto max-w-6xl"><button onClick={() => navigate('/student/scan')} className="mb-6 flex items-center gap-2 text-sm text-signal-blue"><ArrowLeft size={16}/>Back to Scanner</button><h1 className="text-2xl font-bold text-white">My Attendance</h1><p className="mt-1 text-sm text-slate-400">{data ? `${data.student.rollNo} · ${data.student.batchName}` : 'Loading attendance history…'}</p>{error && <p className="mt-5 text-red-300">{error}</p>}
    {data && <><div className="mt-7 grid gap-4 md:grid-cols-3">{data.subjects.map((subject) => <div key={subject.code} className={`rounded-2xl border p-5 ${subject.shortage ? 'border-signal-red/30 bg-signal-red/10' : 'border-ink-border bg-ink-850/60'}`}><div className="flex justify-between"><BookOpen className="text-signal-blue" size={20}/>{subject.shortage && <ShieldAlert className="text-signal-red" size={20}/>}</div><h2 className="mt-3 font-bold text-white">{subject.code} · {subject.name}</h2><p className={`mt-2 text-3xl font-bold ${subject.shortage ? 'text-signal-red' : 'text-signal-green'}`}>{subject.percentage}%</p><p className="mt-1 text-xs text-slate-400">{subject.present} present · {subject.absent} absent · {subject.total} sessions</p>{subject.shortage && <p className="mt-3 text-xs font-semibold text-red-300">Below 75% attendance requirement</p>}</div>)}</div>
    <div className="mt-7 overflow-x-auto rounded-2xl border border-ink-border bg-ink-850/60"><table className="w-full min-w-[720px] text-sm"><thead><tr>{['Date','Subject','Faculty','Status','Check-in'].map((x) => <th key={x} className="px-4 py-3 text-left text-slate-400">{x}</th>)}</tr></thead><tbody>{data.sessions.map((session) => <tr key={session.sessionId} className="border-t border-ink-border"><td className="px-4 py-3">{new Date(session.startedAt).toLocaleString('en-IN')}</td><td className="px-4 py-3 font-bold text-white">{session.subjectCode}</td><td className="px-4 py-3">{session.facultyName}</td><td className={`px-4 py-3 font-bold ${session.status === 'PRESENT' ? 'text-signal-green' : 'text-signal-red'}`}>{session.status}</td><td className="px-4 py-3">{session.scanTime ? new Date(session.scanTime).toLocaleTimeString('en-IN') : '—'}</td></tr>)}</tbody></table></div></>}
  </main></div>;
}
