ALTER TABLE "faculty" ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "admin" ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "student" ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "batch" ADD COLUMN "department" TEXT NOT NULL DEFAULT 'Computer Applications';
ALTER TABLE "batch" ADD COLUMN "programme" TEXT NOT NULL DEFAULT 'MCA';
ALTER TABLE "batch" ADD COLUMN "semester" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "batch" ADD COLUMN "academic_year" TEXT NOT NULL DEFAULT '2026-2027';
ALTER TABLE "attendance_session" ADD COLUMN "scheduled_end_at" TIMESTAMP(3);
ALTER TABLE "attendance_session" ADD COLUMN "session_type" TEXT NOT NULL DEFAULT 'SCHEDULED';
ALTER TABLE "attendance_session" ADD COLUMN "notes" TEXT;

ALTER TYPE "SessionStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'ABSENT';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LATE';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'ON_DUTY';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LEAVE';
